### ISSUE TITLE
Ping me once finished.

### ISSUE THREAD

**Issue by j-yw** [hikaliyana/ScobyHomeWebsite#1]
Good job on completing the website, ping me once you've finished the project. I'll review and share feedbacks.

some optional but nice to try tasks.

- [x] deploy the website to netlify.com (use drag and drop, no need for concurrent build)
- [x] comment on this issue with the website url

**Comment by hikaliyana** [comment]
https://scobyhome.netlify.app/
https://roughmonth.netlify.app/
